name: Trigger Supabase Edge Function on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  trigger-supabase-function:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Trigger Supabase Edge Function
        run: |
          curl -X POST https://zfdttzmqmucctmfvfknd.functions.supabase.co/generate-review \
          -H "Content-Type: application/json" \
          -d '{"pr_number": "${{ github.event.pull_request.number }}"}'
        env:
          SUPABASE_EDGE_FUNCTION_URL: https://zfdttzmqmucctmfvfknd.functions.supabase.co/generate-review
